# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "sigs.k8s.io/controller-tools/pkg/crd/generator",
  "github.com/spf13/cobra"
]

[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.13.1"
  revision = "c2090bec4d9b1fb25de3812f868accc2bc9ecbae"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

[[override]]
  name = "github.com/go-openapi/spec"
  branch = "master"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  version = "=v0.1.10"

[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.13.1"
  revision = "05914d821849570fba9eacfb29466f2d8d3cd229"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # revision for tag "kubernetes-1.13.1"
  revision = "0fe22c71c47604641d9aa352c785b7912c200562"

[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.13.1"
  revision = "2b1284ed4c93a43499e781493253e2ac5959c4fd"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.13.1"
  revision = "8d9ed539ba3134352c586810e749e58df4e94e4f"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.26.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.10"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master" #osdk_branch_annotation
  # version = "=v0.5.0" #osdk_version_annotation

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "10.0.0"

[[override]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

[[override]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[override]]
  name = "github.com/pkg/sftp"
  version = "1.10.0"

[[override]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[override]]
  name = "golang.org/x/crypto"
  branch = "master"

[[override]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[override]]
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/sylabs/singularity-cri"
  version = "1.0.0-beta.1"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

  [[prune.project]]
    name = "sigs.k8s.io/controller-tools"
  	unused-packages = false

  [[prune.project]]
    name = "k8s.io/code-generator"
  	unused-packages = false

  [[prune.project]]
    name = "k8s.io/kube-openapi"
  	unused-packages = false
