apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: slurm-operator
  template:
    metadata:
      labels:
        name: slurm-operator
    spec:
      serviceAccountName: slurm-operator
      containers:
        - name: slurm-operator
          image: sylabsio/slurm:operator
          imagePullPolicy: Always
          args: ["-jc-uid", "1000","-jc-uid", "1000"]
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "slurm-operator"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
